grails-app/domain/com/theendcomplete/UsrOrder.groovy
package com.theendcomplete

import grails.rest.Resource

@Resource()
class UsrOrder {
    Date dateCreated
    Date deadLine
    String status
    def worker

//    static hasOne = [department: Department]
    static hasMany = [items: Item]

    static constraints = {
        worker(nullable: true)
        dateCreated(nullable: true)
        deadLine(nullable: true)
    }

    @Override
    String toString() {
        return id
    }
}

grails-app/controllers/com/theendcomplete/UsrOrderController.groovy
package com.theendcomplete

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class UsrOrderController {

//    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond UsrOrder.list(params), model:[usrOrderCount: UsrOrder.count()]
    }

    def show(UsrOrder usrOrder) {
        respond usrOrder
    }

    def create() {
        respond new UsrOrder(params)
    }

    @Transactional
    def save(UsrOrder usrOrder) {
        if (usrOrder == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (usrOrder.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond usrOrder.errors, view:'create'
            return
        }

        usrOrder.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'usrOrder.label', default: 'UsrOrder'), usrOrder.id])
                redirect usrOrder
            }
            '*' { respond usrOrder, [status: CREATED] }
        }
    }

    def edit(UsrOrder usrOrder) {
        respond usrOrder
    }

    @Transactional
    def update(UsrOrder usrOrder) {
        if (usrOrder == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (usrOrder.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond usrOrder.errors, view:'edit'
            return
        }

        usrOrder.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'usrOrder.label', default: 'UsrOrder'), usrOrder.id])
                redirect usrOrder
            }
            '*'{ respond usrOrder, [status: OK] }
        }
    }

    @Transactional
    def delete(UsrOrder usrOrder) {

        if (usrOrder == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        usrOrder.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'usrOrder.label', default: 'UsrOrder'), usrOrder.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'usrOrder.label', default: 'UsrOrder'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/usrOrder/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'usrOrder.label', default: 'UsrOrder')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-usrOrder" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-usrOrder" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.usrOrder}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.usrOrder}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.usrOrder}" method="POST">
                <fieldset class="form">
                    <f:all bean="usrOrder"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/usrOrder/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'usrOrder.label', default: 'UsrOrder')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-usrOrder" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-usrOrder" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.usrOrder}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.usrOrder}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.usrOrder}" method="PUT">
                <g:hiddenField name="version" value="${this.usrOrder?.version}" />
                <fieldset class="form">
                    <f:all bean="usrOrder"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/usrOrder/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'usrOrder.label', default: 'UsrOrder')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-usrOrder" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-usrOrder" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${usrOrderList}" />

            <div class="pagination">
                <g:paginate total="${usrOrderCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/usrOrder/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'usrOrder.label', default: 'UsrOrder')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-usrOrder" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-usrOrder" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="usrOrder" />
            <g:form resource="${this.usrOrder}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.usrOrder}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>